version: '3.7'

services:

  app_db:
    image: postgres:14-alpine3.16
    container_name: app_db
    expose:
      - 5330
    ports:
      - "5330:5432"
    volumes:
      - ./dbs/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     app
      POSTGRES_PASSWORD: docker
      POSTGRES_DB:       app

  app_redis:
    image: redis:6
    container_name: app_redis
    ports:
      - "6363:6379"

  app_mongodb:
    image: mongo
    container_name: app_mongodb
    ports:
      - "27027:27017"
    volumes:
      - ./dbs/mongo_data:/dbs/mongo_data
    environment:
      MONGO_INITDB_DATABASE: app


  app_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: app_elastic
    ports:
      - "9292:9200"
    volumes:
      - ./dbs/elastic_data:/dbs/elastic_data
    environment:
      - discovery.type=single-node

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: powertofly/skill
    container_name: app
    command:
      - --reload
    depends_on:
      - app_elastic
      - app_mongodb
    ports:
      - "5008:5000"
    volumes:
      - ./app:/opt/powertofly/skill/app
    environment:
      UVICORN_PORT: "5000"
      UVICORN_APP: app.main:app
      UVICORN_WORKERS: 2
    env_file:
      - .env
